# Generated by Django 2.0.6 on 2018-06-18 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('creation_date', models.DateField()),
                ('accounts', models.ManyToManyField(to='studying_2_0_main.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Project_element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('date_added', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='elements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studying_2_0_main.Project_element'),
        ),
    ]
