# Generated by Django 2.0.6 on 2018-06-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studying_2_0_main', '0002_remove_project_elements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_element',
            new_name='ProjectElement',
        ),
    ]
