# Generated by Django 2.0.6 on 2018-06-18 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studying_2_0_main', '0003_auto_20180618_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='elements',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='studying_2_0_main.ProjectElement'),
        ),
    ]
