# Generated by Django 2.0.6 on 2018-07-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studying_2_0_main', '0004_auto_20180730_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectelement',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=30),
        ),
    ]
