# Generated by Django 2.0.6 on 2018-07-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studying_2_0_main', '0005_auto_20180731_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
    ]
