# Generated by Django 2.0.6 on 2018-06-18 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studying_2_0_main', '0012_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='studying_2_0_main.Project'),
        ),
    ]
