# Generated by Django 2.0.6 on 2018-06-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studying_2_0_main', '0013_folder_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectelement',
            name='folder',
            field=models.ManyToManyField(blank=True, null=True, to='studying_2_0_main.Folder'),
        ),
    ]
