# Generated by Django 2.0.6 on 2018-06-18 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studying_2_0_main', '0015_auto_20180618_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studying_2_0_main.Folder'),
        ),
    ]
