# Generated by Django 2.0.6 on 2018-06-18 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studying_2_0_main', '0016_folder_folder_element'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='folder_element',
            new_name='self_elements',
        ),
        migrations.RenameField(
            model_name='projectelement',
            old_name='elements',
            new_name='self_elements',
        ),
        migrations.RemoveField(
            model_name='projectelement',
            name='folder',
        ),
    ]
