# Generated by Django 2.0.6 on 2018-06-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studying_2_0_main', '0017_auto_20180618_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectelement',
            name='folder_element',
            field=models.ManyToManyField(blank=True, to='studying_2_0_main.Folder'),
        ),
    ]
