# Generated by Django 2.0.6 on 2018-06-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studying_2_0_main', '0019_auto_20180619_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='depth',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectelement',
            name='depth',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
