# Generated by Django 2.0.6 on 2018-06-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studying_2_0_main', '0020_auto_20180619_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='depth',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='projectelement',
            name='depth',
            field=models.IntegerField(default=1),
        ),
    ]
