# Generated by Django 2.0.6 on 2018-06-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studying_2_0_main', '0022_auto_20180619_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectelement',
            old_name='folderelement',
            new_name='folder_element',
        ),
    ]
