# Generated by Django 2.0.6 on 2018-06-21 10:38

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studying_2_0_main', '0024_auto_20180621_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectelement',
            name='folder',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children1', to='studying_2_0_main.Folder'),
        ),
    ]
