# Generated by Django 2.0.6 on 2018-06-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studying_2_0_main', '0025_projectelement_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectelement',
            old_name='folder',
            new_name='parent',
        ),
    ]
