# Generated by Django 2.0.6 on 2018-06-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studying_2_0_main', '0026_auto_20180621_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='self_elements',
        ),
        migrations.RemoveField(
            model_name='projectelement',
            name='depth',
        ),
    ]
