# Generated by Django 2.0.6 on 2018-06-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studying_2_0_main', '0027_auto_20180621_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='projectelement',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
