# Generated by Django 2.0.6 on 2018-06-26 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studying_2_0_main', '0029_auto_20180622_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectelement',
            name='folder_element',
        ),
    ]
