# Generated by Django 2.0.6 on 2018-06-26 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studying_2_0_main', '0030_remove_projectelement_folder_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studying_2_0_main.Project'),
        ),
        migrations.AlterField(
            model_name='projectelement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studying_2_0_main.Project'),
        ),
    ]
