# Generated by Django 2.0.6 on 2018-06-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studying_2_0_main', '0031_auto_20180626_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectelement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
