# Generated by Django 2.0.6 on 2018-06-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studying_2_0_main', '0032_projectelement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectelement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
